baseURL = '/'
languageCode = 'pt-pt'
theme = "hello-4s3ti"
title = 'J-PWN'
copyright = "All Rights Reserved"
IsMultiLingual = true
defaultContentLanguage = 'pt-pt'


[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "#"
    weight = 2

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 1
